version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./.tmp/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.tmp/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - net

networks:
  net:
    driver: bridge